# Generated by Django 4.2.1 on 2023-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0002_alter_customuser_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
