# Generated by Django 4.2.1 on 2023-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_remove_book_imageurl_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='fullName',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
