# Generated by Django 4.2.1 on 2023-09-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_alter_book_image_alter_customuser_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.AddField(
            model_name='book',
            name='imageUrl',
            field=models.CharField(default='https://static1.eboighar.com/thumbimages/Books/book_34182019-07-08_1562571894.jpg', max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='imageUrl',
            field=models.CharField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
