# Generated by Django 4.2.1 on 2023-09-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0006_remove_book_image_remove_customuser_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='imageUrl',
            field=models.CharField(max_length=500),
        ),
    ]
