# Generated by Django 4.2.1 on 2023-09-11 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0007_alter_book_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='imageUrl',
        ),
    ]
